Vagrant.configure("2") do |config|
  # Virtual machine
  config.vm.box = "hashicorp/precise64"
  config.vm.network "public_network"

  # Sync
  config.vm.synced_folder "mount/var/www", "/var/www", create: true

  # Shell provisioner
  config.vm.provision "shell", path: "provisioner.sh"
end
